# More info at https://github.com/marketplace/actions/github-labeler
# More info also at https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
# Set update schedule for GitHub Actions

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"

  # Maintain dependencies for npm
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"