name: "Auto Assign"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Assign PR Reviewers
      id: assign-reviewers
      uses: rewindio/auto-assign-reviewer-by-issuer@master
      with:
        config: ${{ secrets.PR_REVIEWERS_CONFIG_FILE_URL }}
        token: ${{ secrets.GITHUB_TOKEN }}